### PR TITLE
Transition from LightnCandy v0.89 to v0.94

### PR DESCRIPTION
**Pull request by Lorti**
Fixed breaking changes introduced by https://github.com/zordius/lightncandy/releases/tag/v0.90 and https://github.com/zordius/lightncandy/releases/tag/v0.91.

### CODE REVIEW

**Comment by Lorti** [comment]
This will fix #11… and possibly #10

**Comment by Lorti** [comment]
I have also taken the liberty to start a test suite and format the files according to PSR-2, so the package follows the same style as Laravel.

**Comment by markusjwetzel** [comment]
Looks great! Tests and PSR-2 compliance were definitely missing. I will merge this pull request and add you as a collaborator to this repository, so you can update it whenever you want. :)

**Comment by Lorti** [comment]
Thanks, that's great! 😄

**Pull request merged**
