### PR TITLE
Upgrade lightncandy to 1.0.*

### PR DESCRIPTION
**Pull request by greut**
Works for me, cheers!

Signed-off-by: Yoan Blanc <yoan@dosimple.ch>

### CODE REVIEW

**Comment by Lorti** [comment]
Thanks! Have you run the PHPUnit tests?

**Comment by greut** [comment]
```
PHPUnit 6.0.5 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 124 ms, Memory: 8.00MB

OK (2 tests, 2 assertions)
```

**Comment by Lorti** [comment]
Awesome, I will create a new release, thank you!

**Comment by greut** [comment]
Great, thanks!

**Pull request merged**
